"use client";

import { useState, useRef, useCallback, useEffect } from "react";
import Image from "next/image";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useLanguage } from "@/lib/LanguageContext";
import StepImage from "./StepImage";
import {
  FileText,
  Printer,
  Download,
  User,
  MapPin,
  Calendar,
  Scale,
  FileSignature,
  ClipboardList,
  Edit3,
  Check,
  Loader2,
} from "lucide-react";

// Title Page Component
function TitlePage({ formData, analysis, formatDate }) {
  const referenceNo = `LEGAIZE-${Date.now().toString().slice(-8)}`;

  return (
    <div
      className="print-document bg-white text-black min-h-[800px] flex flex-col justify-between p-12 border-4 border-double border-gray-800 mb-8 page-break"
      style={{ pageBreakAfter: "always" }}
    >
      {/* Header decoration */}
      <div className="text-center">
        <div className="mb-8">
          <div className="inline-block border-b-4 border-t-4 border-gray-800 py-4 px-8">
            <p className="text-sm tracking-[0.3em] text-gray-600 mb-2">
              REPUBLIC OF THE PHILIPPINES
            </p>
            <p className="text-sm tracking-widest text-gray-500">
              LEGAL DOCUMENTATION
            </p>
          </div>
        </div>
      </div>

      {/* Main Title Section */}
      <div className="text-center flex-1 flex flex-col justify-center">
        {/* Logo */}
        <div className="mb-6">
          <div className="inline-flex items-center justify-center w-32 h-32 rounded-full border-4 border-gray-800 overflow-hidden bg-white">
            {/* Use regular img for print compatibility */}
            <img
              src="/LOGO.png"
              alt="LegAIze Logo"
              width={120}
              height={120}
              className="object-contain p-2"
              style={{ maxWidth: "120px", maxHeight: "120px" }}
            />
          </div>
        </div>

        {/* App Name */}
        <h1
          className="text-5xl font-bold tracking-wide mb-2"
          style={{ fontFamily: "Georgia, serif" }}
        >
          Leg<span className="text-gray-600">AI</span>ze
        </h1>

        {/* Tagline */}
        <p className="text-lg text-gray-600 italic mb-4">
          "Your Legal First AI-d"
        </p>

        {/* Slogan */}
        <p className="text-sm tracking-widest text-gray-500 uppercase mb-12">
          Know Your Rights. LegAIze Your Fight.
        </p>

        {/* Decorative line */}
        <div className="flex items-center justify-center gap-4 mb-12">
          <div className="h-px w-24 bg-gray-400"></div>
          <div className="w-2 h-2 rotate-45 bg-gray-400"></div>
          <div className="h-px w-24 bg-gray-400"></div>
        </div>

        {/* Document Info */}
        <div className="space-y-2">
          <h2 className="text-2xl font-semibold text-gray-800">
            LEGAL CASE DOCUMENTATION
          </h2>
          <p className="text-lg text-gray-600">
            {analysis?.caseType || "Legal Analysis Report"}
          </p>
        </div>
      </div>

      {/* Client & Reference Info */}
      <div className="mt-8">
        <div className="border-t-2 border-gray-300 pt-6">
          <div className="grid grid-cols-2 gap-8 text-sm">
            <div className="text-left">
              <p className="text-gray-500 uppercase text-xs tracking-wider mb-1">
                Prepared For
              </p>
              <p className="font-semibold text-lg">
                {formData.fullName || "[Client Name]"}
              </p>
              <p className="text-gray-600 text-xs mt-1">
                {formData.address || "[Address]"}
              </p>
            </div>
            <div className="text-right">
              <p className="text-gray-500 uppercase text-xs tracking-wider mb-1">
                Reference Number
              </p>
              <p className="font-mono font-semibold">{referenceNo}</p>
              <p className="text-gray-500 uppercase text-xs tracking-wider mt-3 mb-1">
                Date Prepared
              </p>
              <p className="font-semibold">{formatDate(formData.date)}</p>
            </div>
          </div>
        </div>

        {/* Footer note */}
        <div className="mt-8 pt-4 border-t border-gray-200 text-center">
          <p className="text-xs text-gray-500">
            This document was generated by LegAIze - AI-Powered Philippine Legal
            Assistance
          </p>
          <p className="text-xs text-gray-400 mt-1">
            www.legaize.ph • support@legaize.ph
          </p>
        </div>
      </div>
    </div>
  );
}

export default function ReportsGenerator({ analysis }) {
  const { t } = useLanguage();
  const printRef = useRef(null);
  const [activeReport, setActiveReport] = useState("salaysay");
  const [includeTitlePage, setIncludeTitlePage] = useState(true);
  const [formData, setFormData] = useState({
    fullName: "",
    address: "",
    age: "",
    civilStatus: "",
    occupation: "",
    contactNumber: "",
    date: new Date().toISOString().split("T")[0],
    incidentDate: "",
    incidentLocation: "",
    additionalDetails: "",
  });
  const [isEditing, setIsEditing] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const formatDate = (dateString) => {
    if (!dateString) return "_______________";
    const date = new Date(dateString);
    return date.toLocaleDateString("fil-PH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  };

  const formatDateShort = (dateString) => {
    if (!dateString) return "_______________";
    const date = new Date(dateString);
    return date.toLocaleDateString("fil-PH", {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
    });
  };

  // Get the print content element
  const getPrintContent = useCallback(() => {
    const tabContentSelector = `[data-state="active"] .print-wrapper`;
    let activeWrapper = document.querySelector(tabContentSelector);
    if (!activeWrapper) {
      activeWrapper =
        printRef.current || document.querySelector(".print-wrapper");
    }
    return activeWrapper;
  }, []);

  // Common styles for print/PDF
  const getDocumentStyles = () => `
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: "Times New Roman", Times, serif;
      font-size: 12pt;
      line-height: 1.6;
      color: black;
      background: white;
    }
    .print-document {
      background: white;
      color: black;
      padding: 0.5in;
    }
    /* Page break controls */
    .page-break { page-break-before: always; }
    .no-break { page-break-inside: avoid; }
    .print-document > div { page-break-inside: avoid; }
    
    h1 { font-size: 16pt; margin-bottom: 12pt; page-break-after: avoid; }
    h2 { font-size: 14pt; margin-top: 16pt; margin-bottom: 8pt; page-break-after: avoid; }
    p { margin-bottom: 8pt; text-align: justify; orphans: 3; widows: 3; }
    ul, ol { margin-left: 20pt; margin-bottom: 8pt; }
    li { margin-bottom: 4pt; }
    .text-center { text-align: center; }
    .text-right { text-align: right; }
    .text-justify { text-align: justify; }
    .font-bold, strong { font-weight: bold; }
    .font-semibold { font-weight: 600; }
    .italic, em { font-style: italic; }
    .underline { text-decoration: underline; }
    .uppercase { text-transform: uppercase; }
    .tracking-wide { letter-spacing: 0.05em; }
    .tracking-widest { letter-spacing: 0.1em; }
    .mb-2 { margin-bottom: 8pt; }
    .mb-4 { margin-bottom: 16pt; }
    .mb-6 { margin-bottom: 24pt; }
    .mb-8 { margin-bottom: 32pt; }
    .mt-4 { margin-top: 16pt; }
    .mt-8 { margin-top: 32pt; }
    .mt-12 { margin-top: 48pt; }
    .mt-16 { margin-top: 64pt; }
    .pt-4 { padding-top: 16pt; }
    .pt-6 { padding-top: 24pt; }
    .pt-8 { padding-top: 32pt; }
    .pl-4 { padding-left: 16pt; }
    .pl-8 { padding-left: 32pt; }
    .p-4 { padding: 16pt; }
    .p-8 { padding: 32pt; }
    .p-12 { padding: 48pt; }
    .space-y-2 > * + * { margin-top: 8pt; }
    .space-y-4 > * + * { margin-top: 16pt; }
    .space-y-6 > * + * { margin-top: 24pt; }
    .border-t { border-top: 1pt solid #ccc; }
    .border-b { border-bottom: 1pt solid #ccc; }
    .border-t-2 { border-top: 2pt solid #333; }
    .border-b-2 { border-bottom: 2pt solid #333; }
    .border-t-4 { border-top: 4pt solid #333; }
    .border-b-4 { border-bottom: 4pt solid #333; }
    .border-4 { border: 4pt solid #333; }
    .border-double { border-style: double; }
    .border-l-4 { border-left: 4pt solid #666; }
    .rounded-full { border-radius: 50%; }
    .rounded-lg { border-radius: 8pt; }
    .bg-gray-50 { background: #f5f5f5; }
    .text-gray-400 { color: #9ca3af; }
    .text-gray-500 { color: #6b7280; }
    .text-gray-600 { color: #4b5563; }
    .text-gray-700 { color: #374151; }
    .text-gray-800 { color: #1f2937; }
    .text-sm { font-size: 10pt; }
    .text-xs { font-size: 8pt; }
    .text-lg { font-size: 14pt; }
    .text-xl { font-size: 16pt; }
    .text-2xl { font-size: 18pt; }
    .text-4xl { font-size: 28pt; }
    .text-5xl { font-size: 36pt; }
    .flex { display: flex; }
    .flex-col { flex-direction: column; }
    .flex-1 { flex: 1; }
    .items-center { align-items: center; }
    .justify-center { justify-content: center; }
    .justify-between { justify-content: space-between; }
    .gap-2 { gap: 8pt; }
    .gap-4 { gap: 16pt; }
    .gap-8 { gap: 32pt; }
    .grid { display: grid; }
    .grid-cols-2 { grid-template-columns: repeat(2, 1fr); }
    .col-span-2 { grid-column: span 2; }
    .inline-block { display: inline-block; }
    .inline-flex { display: inline-flex; }
    .w-48 { width: 192pt; }
    .w-24 { width: 96pt; }
    .w-20 { width: 80pt; }
    .w-32 { width: 128pt; }
    .w-2 { width: 8pt; }
    .h-2 { height: 8pt; }
    .h-px { height: 1px; }
    .min-h-\\[100px\\] { min-height: 100px; }
    .min-h-\\[800px\\] { min-height: auto; }
    .rotate-45 { transform: rotate(45deg); }
    .list-disc { list-style-type: disc; }
    .list-decimal { list-style-type: decimal; }
    img { max-width: 100%; height: auto; }
    .overflow-hidden { overflow: hidden; }
    .object-contain { object-fit: contain; }
    @media print {
      @page { size: letter; margin: 0.75in; }
      body { padding: 0; }
    }
  `;

  // Print function - opens print dialog
  const handlePrint = () => {
    const activeWrapper = getPrintContent();
    if (!activeWrapper) {
      window.print();
      return;
    }

    const printContent = activeWrapper.innerHTML;
    const printWindow = window.open("", "_blank", "width=800,height=600");

    if (!printWindow) {
      window.print();
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>LegAIze - ${
            activeReport === "salaysay"
              ? "Salaysay"
              : activeReport === "summary"
              ? "Case Summary"
              : "Legal Brief"
          }</title>
          <style>${getDocumentStyles()}</style>
        </head>
        <body>${printContent}</body>
      </html>
    `);
    printWindow.document.close();

    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 250);
    };
  };

  // Helper function to split text into lines that fit within width
  const splitText = (pdf, text, maxWidth, x, y) => {
    const lines = pdf.splitTextToSize(text, maxWidth);
    return { lines, height: lines.length * pdf.getLineHeight() };
  };

  // Helper function to add text with word wrap
  const addWrappedText = (pdf, text, x, y, maxWidth, fontSize = 11) => {
    pdf.setFontSize(fontSize);
    const { lines } = splitText(pdf, text, maxWidth);
    lines.forEach((line, index) => {
      pdf.text(line, x, y + index * (fontSize * 1.2));
    });
    return y + lines.length * (fontSize * 1.2);
  };

  // Generate Title Page
  const generateTitlePage = async (pdf, pageWidth, pageHeight) => {
    const referenceNo = `LEGAIZE-${Date.now().toString().slice(-8)}`;

    pdf.setFillColor(255, 255, 255);
    pdf.rect(0, 0, pageWidth, pageHeight, "F");

    // Header decoration
    pdf.setFontSize(10);
    pdf.setTextColor(0, 0, 0);
    pdf.text("REPUBLIC OF THE PHILIPPINES", pageWidth / 2, 100, {
      align: "center",
    });
    pdf.text("LEGAL DOCUMENTATION", pageWidth / 2, 115, { align: "center" });

    // Logo (centered)
    const logoSize = 80;
    try {
      // Load logo image using fetch and convert to base64
      const response = await fetch("/LOGO.png");
      if (response.ok) {
        const blob = await response.blob();
        const reader = new FileReader();
        await new Promise((resolve, reject) => {
          reader.onload = () => {
            try {
              const imgData = reader.result;
              // Calculate aspect ratio to maintain logo proportions
              // Use native browser Image constructor (not Next.js Image component)
              const logoImg = new window.Image();
              logoImg.src = imgData;
              logoImg.onload = () => {
                const aspectRatio = logoImg.width / logoImg.height;
                const logoWidth = logoSize * aspectRatio;
                const logoHeight = logoSize;
                pdf.addImage(
                  imgData,
                  "PNG",
                  pageWidth / 2 - logoWidth / 2,
                  160,
                  logoWidth,
                  logoHeight
                );
                resolve();
              };
              logoImg.onerror = () => resolve();
            } catch (err) {
              console.warn("Could not add logo image:", err);
              resolve();
            }
          };
          reader.onerror = () => resolve();
          reader.readAsDataURL(blob);
        });
      }
    } catch (err) {
      console.warn("Error loading logo:", err);
    }

    // App Name
    pdf.setFontSize(36);
    pdf.setTextColor(0, 0, 0);
    pdf.setFont("helvetica", "bold");
    pdf.text("LegAIze", pageWidth / 2, 320, { align: "center" });

    // Tagline
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "italic");
    pdf.setTextColor(0, 0, 0);
    pdf.text('"Your Legal First AI-d"', pageWidth / 2, 345, {
      align: "center",
    });

    // Slogan
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text("Know Your Rights. LegAIze Your Fight.", pageWidth / 2, 380, {
      align: "center",
    });

    // Document Info
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text("LEGAL CASE DOCUMENTATION", pageWidth / 2, 450, {
      align: "center",
    });

    pdf.setFontSize(14);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      analysis?.caseType || "Legal Analysis Report",
      pageWidth / 2,
      475,
      { align: "center" }
    );

    // Client & Reference Info
    const infoY = 600;
    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.text("PREPARED FOR", 60, infoY);
    pdf.setFontSize(12);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text(formData.fullName || "[Client Name]", 60, infoY + 15);
    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.text(formData.address || "[Address]", 60, infoY + 30);

    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.text("REFERENCE NUMBER", pageWidth - 60, infoY, { align: "right" });
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text(referenceNo, pageWidth - 60, infoY + 15, { align: "right" });
    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.text("DATE PREPARED", pageWidth - 60, infoY + 35, { align: "right" });
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text(formatDate(formData.date), pageWidth - 60, infoY + 50, {
      align: "right",
    });

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.text(
      "This document was generated by LegAIze - AI-Powered Philippine Legal Assistance",
      pageWidth / 2,
      pageHeight - 40,
      { align: "center" }
    );
    pdf.text(
      "www.legaize.ph • support@legaize.ph",
      pageWidth / 2,
      pageHeight - 25,
      { align: "center" }
    );
  };

  // Generate Salaysay Document
  const generateSalaysay = (pdf, pageWidth, pageHeight, margin) => {
    let y = margin + 20;

    // Title
    pdf.setFontSize(18);
    pdf.setFont("helvetica", "bold");
    pdf.text("SINUMPAANG SALAYSAY", pageWidth / 2, y, { align: "center" });
    y += 20;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");
    pdf.text("(Sworn Statement)", pageWidth / 2, y, { align: "center" });
    y += 30;

    // Opening statement
    pdf.setFontSize(11);
    const openingText =
      `AKO, si ${formData.fullName || "________________________"}, ` +
      `${
        formData.age ? `${formData.age} taong gulang` : "_____ taong gulang"
      }, ` +
      `${formData.civilStatus || "_____________"}, ` +
      `${
        formData.occupation ? `${formData.occupation}` : "_____________"
      } ang hanapbuhay, ` +
      `at kasalukuyang naninirahan sa ${
        formData.address || "________________________________________________"
      }, ` +
      `matapos makapanumpa ng naaayon sa batas, ay malaya at kusang-loob na nagpapahayag ng mga sumusunod:`;

    y = addWrappedText(pdf, openingText, margin, y, pageWidth - margin * 2, 11);
    y += 15;

    // Item 1
    pdf.setFont("helvetica", "bold");
    pdf.text("1.", margin, y);
    const item1Text = `Na noong ${formatDate(formData.incidentDate)}, sa ${
      formData.incidentLocation || "________________________"
    }, ay naganap ang mga sumusunod na pangyayari:`;
    y = addWrappedText(
      pdf,
      item1Text,
      margin + 20,
      y - 11,
      pageWidth - margin * 2 - 20,
      11
    );
    y += 10;

    // Case details box
    const boxY = y;
    pdf.setFillColor(245, 245, 245);
    pdf.rect(margin + 20, boxY, pageWidth - margin * 2 - 40, 60, "F");
    pdf.setDrawColor(200, 200, 200);
    pdf.rect(margin + 20, boxY, pageWidth - margin * 2 - 40, 60, "S");

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    let detailY = boxY + 10;
    if (analysis?.caseType) {
      pdf.setFont("helvetica", "bold");
      pdf.text(`Uri ng Kaso: ${analysis.caseType}`, margin + 30, detailY);
      detailY += 12;
    }
    pdf.setFont("helvetica", "normal");
    const details =
      formData.additionalDetails ||
      "[Ilagay dito ang detalyadong salaysay ng pangyayari]";
    const detailLines = pdf.splitTextToSize(
      details,
      pageWidth - margin * 2 - 60
    );
    detailLines.forEach((line, idx) => {
      pdf.text(line, margin + 30, detailY + idx * 10);
    });
    y = boxY + 70;

    // Item 2 - Rights
    y += 10;
    pdf.setFont("helvetica", "bold");
    pdf.text("2.", margin, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "Na ang mga sumusunod ay ang aking mga karapatan kaugnay sa nasabing pangyayari:",
      margin + 20,
      y
    );
    y += 15;

    if (analysis?.rights && analysis.rights.length > 0) {
      analysis.rights.forEach((right, index) => {
        pdf.setFontSize(10);
        pdf.text(`• ${right}`, margin + 30, y);
        y += 12;
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
      });
    }

    // Item 3 - Laws
    y += 10;
    pdf.setFont("helvetica", "bold");
    pdf.text("3.", margin, y);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "Na ang mga sumusunod na batas ay maaaring naaangkop sa aking kaso:",
      margin + 20,
      y
    );
    y += 15;

    if (analysis?.relevantLaws && analysis.relevantLaws.length > 0) {
      analysis.relevantLaws.slice(0, 5).forEach((law, index) => {
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "bold");
        pdf.text(`${law.title || law.name}`, margin + 30, y);
        y += 10;
        if (law.law || law.article) {
          pdf.setFont("helvetica", "normal");
          pdf.text(`- ${law.law || law.article}`, margin + 40, y);
          y += 10;
        }
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
      });
    }

    // Item 4 & 5
    y += 10;
    pdf.setFont("helvetica", "bold");
    pdf.text("4.", margin, y);
    pdf.setFont("helvetica", "normal");
    const item4Text =
      "Na ang lahat ng aking sinabi sa salaysay na ito ay pawang katotohanan at wala akong idinagdag o inalis na anuman.";
    y = addWrappedText(
      pdf,
      item4Text,
      margin + 20,
      y - 11,
      pageWidth - margin * 2 - 20,
      11
    );
    y += 15;

    pdf.setFont("helvetica", "bold");
    pdf.text("5.", margin, y);
    pdf.setFont("helvetica", "normal");
    const item5Text =
      "Na ginawa ko ang salaysay na ito upang magsilbing patunay sa anumang legal na aksyon na maaaring isagawa kaugnay ng nasabing pangyayari.";
    y = addWrappedText(
      pdf,
      item5Text,
      margin + 20,
      y - 11,
      pageWidth - margin * 2 - 20,
      11
    );
    y += 20;

    // Closing statement
    pdf.setFont("helvetica", "bold");
    const closingText = `SA KATUNAYAN NG LAHAT NG ITO, ako ay lumagda sa ibaba nito ngayong ${formatDate(
      formData.date
    )}, dito sa ${
      formData.address?.split(",").pop()?.trim() || "________________________"
    }, Pilipinas.`;
    y = addWrappedText(pdf, closingText, margin, y, pageWidth - margin * 2, 11);
    y += 30;

    // Signature area
    if (y > pageHeight - 120) {
      pdf.addPage();
      y = margin + 20;
    }

    pdf.setDrawColor(0, 0, 0);
    pdf.line(margin, y, margin + 200, y);
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text(
      (formData.fullName || "PANGALAN NG NAGPAPAHAYAG").toUpperCase(),
      margin,
      y + 10
    );
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text("Nagpapahayag/Affiant", margin, y + 18);

    pdf.line(pageWidth - margin - 200, y, pageWidth - margin, y);
    pdf.text("Petsa/Date", pageWidth - margin - 200, y + 10);

    y += 40;

    // Notary section
    if (y > pageHeight - 100) {
      pdf.addPage();
      y = margin + 20;
    }

    pdf.setFontSize(10);
    pdf.setFont("helvetica", "bold");
    pdf.text("PAGPAPATUNAY NG NOTARYO PUBLIKO", pageWidth / 2, y, {
      align: "center",
    });
    y += 15;

    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    const notaryText =
      "SUBSCRIBED AND SWORN to before me this _____ day of _______________, 20_____ at _________________________, Philippines, affiant exhibiting to me his/her valid government-issued ID No. ________________________ issued on __________________ at ________________________.";
    y = addWrappedText(pdf, notaryText, margin, y, pageWidth - margin * 2, 8);
    y += 20;

    pdf.line(pageWidth / 2 - 100, y, pageWidth / 2 + 100, y);
    pdf.setFontSize(10);
    pdf.text("NOTARYO PUBLIKO/Notary Public", pageWidth / 2, y + 10, {
      align: "center",
    });
    pdf.setFontSize(8);
    pdf.text(
      "Doc. No. _____; Page No. _____; Book No. _____; Series of 20_____.",
      pageWidth / 2,
      y + 25,
      { align: "center" }
    );
  };

  // Generate Case Summary Document
  const generateCaseSummary = (pdf, pageWidth, pageHeight, margin) => {
    let y = margin + 20;

    // Title
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text("CASE SUMMARY REPORT", pageWidth / 2, y, { align: "center" });
    y += 15;
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    pdf.text("Legal Analysis and Recommendations", pageWidth / 2, y, {
      align: "center",
    });
    y += 25;

    // Report Date and Reference
    pdf.setFontSize(9);
    pdf.text(`Report Date: ${formatDate(formData.date)}`, margin, y);
    pdf.text(
      `Reference No: CASE-${Date.now().toString().slice(-8)}`,
      pageWidth - margin,
      y,
      { align: "right" }
    );
    y += 20;

    // Client Information Section
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.text("I. CLIENT INFORMATION", margin, y);
    y += 15;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setFillColor(245, 245, 245);
    pdf.rect(margin, y, pageWidth - margin * 2, 80, "F");
    pdf.text(`Name: ${formData.fullName || "N/A"}`, margin + 10, y + 12);
    pdf.text(`Age: ${formData.age || "N/A"}`, margin + 10, y + 24);
    pdf.text(`Address: ${formData.address || "N/A"}`, margin + 10, y + 36);
    pdf.text(
      `Contact: ${formData.contactNumber || "N/A"}`,
      margin + 10,
      y + 48
    );
    pdf.text(
      `Incident Date: ${formatDate(formData.incidentDate) || "N/A"}`,
      margin + 10,
      y + 60
    );
    y += 90;

    // Case Overview
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    const caseOverviewNum =
      analysis?.followUpQuestions && analysis.followUpQuestions.length > 0
        ? "III"
        : "II";
    pdf.text(`${caseOverviewNum}. CASE OVERVIEW`, margin, y);
    y += 15;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.setFillColor(245, 245, 245);
    pdf.rect(margin, y, pageWidth - margin * 2, 50, "F");
    pdf.text(
      `Case Type: ${analysis?.caseType || "General Legal Inquiry"}`,
      margin + 10,
      y + 12
    );
    pdf.text(`Severity Level: ${getSeverityText()}`, margin + 10, y + 24);
    pdf.text(
      `Location: ${formData.incidentLocation || "Not specified"}`,
      margin + 10,
      y + 36
    );
    y += 60;

    // Follow-up Questions & Answers
    if (analysis?.followUpQuestions && analysis.followUpQuestions.length > 0) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.text("II. ADDITIONAL INFORMATION", margin, y);
      y += 15;
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      pdf.text(
        "The following information was gathered through follow-up questions:",
        margin + 10,
        y
      );
      y += 12;

      analysis.followUpQuestions.forEach((qa, index) => {
        if (y > pageHeight - margin - 80) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.setFillColor(245, 245, 245);
        pdf.rect(margin, y, pageWidth - margin * 2, 50, "F");
        pdf.setFont("helvetica", "bold");
        pdf.text(`Q${index + 1}: ${qa.question}`, margin + 10, y + 12);
        pdf.setFont("helvetica", "normal");
        const answerLines = pdf.splitTextToSize(
          qa.answer || "No answer provided",
          pageWidth - margin * 2 - 20
        );
        pdf.text(answerLines, margin + 10, y + 24);
        y += 15 + answerLines.length * 8;
      });
      y += 10;
    }

    // Applicable Laws
    if (analysis?.relevantLaws && analysis.relevantLaws.length > 0) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      const lawsNum =
        analysis?.followUpQuestions && analysis.followUpQuestions.length > 0
          ? "IV"
          : "III";
      pdf.text(`${lawsNum}. APPLICABLE LAWS`, margin, y);
      y += 15;
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      analysis.relevantLaws.forEach((law) => {
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.setFillColor(245, 245, 245);
        pdf.rect(margin, y, pageWidth - margin * 2, 40, "F");
        pdf.setFont("helvetica", "bold");
        pdf.text(law.title || law.name, margin + 10, y + 12);
        if (law.law || law.article) {
          pdf.setFont("helvetica", "normal");
          pdf.text(law.law || law.article, margin + 10, y + 24);
        }
        y += 45;
      });
    }

    // Client Rights
    if (analysis?.rights && analysis.rights.length > 0) {
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      const rightsNum =
        analysis?.followUpQuestions && analysis.followUpQuestions.length > 0
          ? "V"
          : "IV";
      pdf.text(`${rightsNum}. CLIENT RIGHTS`, margin, y);
      y += 15;
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");
      analysis.rights.forEach((right) => {
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.text(`• ${right}`, margin + 10, y);
        y += 12;
      });
    }

    // Recommended Actions
    if (analysis?.nextSteps && analysis.nextSteps.length > 0) {
      y += 10;
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      const actionsNum =
        analysis?.followUpQuestions && analysis.followUpQuestions.length > 0
          ? "VI"
          : "V";
      pdf.text(`${actionsNum}. RECOMMENDED ACTIONS`, margin, y);
      y += 15;
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "normal");

      for (let index = 0; index < analysis.nextSteps.length; index++) {
        const step = analysis.nextSteps[index];
        if (y > pageHeight - margin - 80) {
          pdf.addPage();
          y = margin + 20;
        }

        // Add step image placeholder (simplified for PDF)
        const imageX = margin + 10;
        const imageY = y - 5;
        const imageWidth = 50;
        const imageHeight = 35;

        // Draw a visual box for the step
        pdf.setFillColor(59, 130, 246);
        pdf.roundedRect(imageX, imageY, imageWidth, imageHeight, 3, 3, "F");
        pdf.setFillColor(255, 255, 255);
        pdf.setFontSize(10);
        pdf.setFont("helvetica", "bold");
        pdf.text(
          `${index + 1}`,
          imageX + imageWidth / 2,
          imageY + imageHeight / 2,
          { align: "center" }
        );

        // Add step text next to image
        const textX = imageX + imageWidth + 10;
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
        y = addWrappedText(
          pdf,
          step.action,
          textX,
          y,
          pageWidth - textX - margin,
          9
        );

        if (step.deadline) {
          pdf.setFontSize(8);
          pdf.setTextColor(100, 100, 100);
          pdf.text(`Deadline: ${step.deadline}`, textX, y + 5);
          pdf.setTextColor(0, 0, 0);
          y += 15;
        } else {
          y += 8;
        }
      }
    }

    // Disclaimer
    y += 20;
    if (y > pageHeight - margin - 80) {
      pdf.addPage();
      y = margin + 20;
    }
    pdf.setFontSize(8);
    pdf.setTextColor(0, 0, 0);
    pdf.setDrawColor(0, 0, 0);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 10;
    const disclaimerText =
      "DISCLAIMER: This report is generated for informational purposes only and does not constitute legal advice. Please consult with a licensed attorney for professional legal counsel.";
    const disclaimerLines = pdf.splitTextToSize(
      disclaimerText,
      pageWidth - margin * 2
    );
    disclaimerLines.forEach((line, idx) => {
      pdf.text(line, pageWidth / 2, y + idx * 10, { align: "center" });
    });
  };

  // Generate Legal Brief Document
  const generateLegalBrief = (pdf, pageWidth, pageHeight, margin) => {
    let y = margin + 20;

    // Header
    pdf.setFontSize(9);
    pdf.setTextColor(0, 0, 0);
    pdf.text("Republic of the Philippines", pageWidth / 2, y, {
      align: "center",
    });
    y += 12;
    pdf.text("OFFICE OF THE LEGAL COUNSEL", pageWidth / 2, y, {
      align: "center",
    });
    y += 20;

    // Title
    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(0, 0, 0);
    pdf.text("LEGAL MEMORANDUM", pageWidth / 2, y, { align: "center" });
    pdf.setDrawColor(0, 0, 0);
    pdf.line(pageWidth / 2 - 100, y + 5, pageWidth / 2 + 100, y + 5);
    y += 30;

    // To/From/Date/RE
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      `TO: ${(formData.fullName || "[CLIENT NAME]").toUpperCase()}`,
      margin,
      y
    );
    y += 12;
    pdf.text("FROM: Legal Analysis System", margin, y);
    y += 12;
    pdf.text(`DATE: ${formatDate(formData.date)}`, margin, y);
    y += 12;
    pdf.setFont("helvetica", "bold");
    pdf.text(
      `RE: ${
        analysis?.caseType || "Legal Matter"
      } - Legal Analysis and Opinion`,
      margin,
      y
    );
    y += 20;

    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 20;

    // Statement of Facts
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.text("I. STATEMENT OF FACTS", margin, y);
    y += 15;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    let factsText = `The client, ${formData.fullName || "[Client Name]"}`;
    if (formData.age) {
      factsText += `, ${formData.age} years of age`;
    }
    factsText += `, residing at ${
      formData.address || "[Address]"
    }, seeks legal advice regarding a matter classified as ${
      analysis?.caseType || "a legal concern"
    }`;
    if (formData.incidentDate) {
      factsText += `. The incident in question occurred on ${formatDate(
        formData.incidentDate
      )}`;
    }
    if (formData.incidentLocation) {
      factsText += ` at ${formData.incidentLocation}`;
    }
    factsText += ".";
    y = addWrappedText(
      pdf,
      factsText,
      margin + 20,
      y,
      pageWidth - margin * 2 - 20,
      9
    );
    if (formData.additionalDetails) {
      y += 10;
      y = addWrappedText(
        pdf,
        `Additional details: ${formData.additionalDetails}`,
        margin + 20,
        y,
        pageWidth - margin * 2 - 20,
        9
      );
    }
    y += 20;

    // Issues
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.text("II. ISSUES", margin, y);
    y += 15;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    const issues = [
      "What are the legal rights of the client under the circumstances?",
      "What laws and regulations are applicable to this case?",
      "What are the recommended courses of action?",
    ];
    issues.forEach((issue, idx) => {
      pdf.text(`${idx + 1}. ${issue}`, margin + 20, y);
      y += 12;
    });
    y += 10;

    // Discussion
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.text("III. DISCUSSION", margin, y);
    y += 15;

    // Applicable Laws
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "bold");
    pdf.text("A. Applicable Laws and Jurisprudence", margin + 20, y);
    y += 12;
    pdf.setFont("helvetica", "normal");
    if (analysis?.relevantLaws && analysis.relevantLaws.length > 0) {
      analysis.relevantLaws.forEach((law, index) => {
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.text(`${index + 1}. ${law.title || law.name}`, margin + 30, y);
        y += 10;
        if (law.law || law.article) {
          pdf.setTextColor(0, 0, 0);
          pdf.text(`(${law.law || law.article})`, margin + 40, y);
          pdf.setTextColor(0, 0, 0);
          y += 10;
        }
        if (law.description) {
          pdf.text(`- ${law.description}`, margin + 40, y);
          y += 10;
        }
        y += 5;
      });
    }

    // Rights
    y += 10;
    pdf.setFont("helvetica", "bold");
    pdf.text("B. Rights of the Client", margin + 20, y);
    y += 12;
    pdf.setFont("helvetica", "normal");
    if (analysis?.rights && analysis.rights.length > 0) {
      analysis.rights.forEach((right) => {
        if (y > pageHeight - margin - 50) {
          pdf.addPage();
          y = margin + 20;
        }
        pdf.text(`• ${right}`, margin + 30, y);
        y += 12;
      });
    }

    // Conclusion
    y += 15;
    pdf.setFontSize(11);
    pdf.setFont("helvetica", "bold");
    pdf.text("IV. CONCLUSION AND RECOMMENDATIONS", margin, y);
    y += 15;
    pdf.setFontSize(9);
    pdf.setFont("helvetica", "normal");
    pdf.text(
      "Based on the foregoing analysis, it is respectfully recommended that the client:",
      margin,
      y
    );
    y += 15;

    if (analysis?.nextSteps && analysis.nextSteps.length > 0) {
      for (let index = 0; index < analysis.nextSteps.length; index++) {
        const step = analysis.nextSteps[index];
        if (y > pageHeight - margin - 80) {
          pdf.addPage();
          y = margin + 20;
        }

        // Add step image placeholder
        const imageX = margin + 20;
        const imageY = y - 5;
        const imageWidth = 40;
        const imageHeight = 30;

        pdf.setFillColor(59, 130, 246);
        pdf.roundedRect(imageX, imageY, imageWidth, imageHeight, 3, 3, "F");
        pdf.setFillColor(255, 255, 255);
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "bold");
        pdf.text(
          `${index + 1}`,
          imageX + imageWidth / 2,
          imageY + imageHeight / 2,
          { align: "center" }
        );

        // Add step text
        const textX = imageX + imageWidth + 10;
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
        y = addWrappedText(
          pdf,
          `${step.action}${step.priority === "high" ? " (URGENT)" : ""}`,
          textX,
          y,
          pageWidth - textX - margin,
          9
        );
        y += 8;
      }
    }

    // Signature
    y += 20;
    if (y > pageHeight - margin - 80) {
      pdf.addPage();
      y = margin + 20;
    }
    pdf.text("Respectfully submitted,", pageWidth - margin, y, {
      align: "right",
    });
    y += 30;
    pdf.setDrawColor(0, 0, 0);
    pdf.line(pageWidth - margin - 200, y, pageWidth - margin, y);
    pdf.setFont("helvetica", "bold");
    pdf.text("Legal Analysis System", pageWidth - margin - 200, y + 10);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(0, 0, 0);
    pdf.text("AI-Powered Legal Assistant", pageWidth - margin - 200, y + 20);
  };

  // Download PDF function - generates PDF directly from data
  const handleDownloadPDF = async () => {
    setIsDownloading(true);

    try {
      // Get filename
      const reportNames = {
        salaysay: "Sinumpaang_Salaysay",
        summary: "Case_Summary",
        legal: "Legal_Brief",
      };
      const userName = formData.fullName?.replace(/\s+/g, "_") || "Document";
      const filename = `LegAIze_${
        reportNames[activeReport] || "Report"
      }_${userName}_${new Date().toISOString().split("T")[0]}.pdf`;

      // Import jsPDF
      const jspdfModule = await import("jspdf");
      const jsPDF = jspdfModule.jsPDF || jspdfModule.default;

      // Create PDF
      const pdf = new jsPDF({
        unit: "pt",
        format: "letter",
        orientation: "portrait",
      });

      const pageWidth = 612;
      const pageHeight = 792;
      const margin = 40;

      // Add title page if enabled
      if (includeTitlePage) {
        await generateTitlePage(pdf, pageWidth, pageHeight);
        pdf.addPage();
      }

      // Generate content based on active report type
      if (activeReport === "salaysay") {
        generateSalaysay(pdf, pageWidth, pageHeight, margin);
      } else if (activeReport === "summary") {
        generateCaseSummary(pdf, pageWidth, pageHeight, margin);
      } else if (activeReport === "legal") {
        generateLegalBrief(pdf, pageWidth, pageHeight, margin);
      }

      // Add page numbers
      const pageCount = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(0, 0, 0);
        pdf.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 25, {
          align: "center",
        });
      }

      // Save PDF
      pdf.save(filename);
    } catch (error) {
      console.error("PDF generation error:", error);
      alert("Error generating PDF. Using print dialog instead.");
      handlePrint();
    } finally {
      setIsDownloading(false);
    }
  };

  const getSeverityText = () => {
    const rating =
      typeof analysis?.severity === "string"
        ? analysis.severity
        : analysis?.severity?.rating;

    switch (rating?.toLowerCase()) {
      case "high":
        return "Mataas (High)";
      case "medium":
        return "Katamtaman (Medium)";
      case "low":
        return "Mababa (Low)";
      default:
        return "Hindi Natukoy";
    }
  };

  return (
    <div className="space-y-6">
      {/* Form Fields Card */}
      <Card className="card-hover no-print">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2 text-lg">
              <User className="h-5 w-5 text-primary" />
              {t("personalInformation") || "Personal Information"}
            </CardTitle>
            <Button
              variant={isEditing ? "default" : "outline"}
              size="sm"
              onClick={() => setIsEditing(!isEditing)}
              className="gap-2"
            >
              {isEditing ? (
                <>
                  <Check className="h-4 w-4" />
                  {t("done") || "Done"}
                </>
              ) : (
                <>
                  <Edit3 className="h-4 w-4" />
                  {t("edit") || "Edit"}
                </>
              )}
            </Button>
          </div>
          <p className="text-sm text-muted-foreground mt-1">
            {t("fillFormForReports") ||
              "Fill in your information to generate formal legal documents"}
          </p>
        </CardHeader>
        <CardContent>
          {isEditing ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="fullName">
                  {t("fullName") || "Full Name"} *
                </Label>
                <Input
                  id="fullName"
                  placeholder="Juan Dela Cruz"
                  value={formData.fullName}
                  onChange={(e) =>
                    handleInputChange("fullName", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="age">{t("age") || "Age"}</Label>
                <Input
                  id="age"
                  type="number"
                  placeholder="30"
                  value={formData.age}
                  onChange={(e) => handleInputChange("age", e.target.value)}
                />
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="address">
                  {t("completeAddress") || "Complete Address"} *
                </Label>
                <Input
                  id="address"
                  placeholder="123 Sample Street, Barangay, City, Province"
                  value={formData.address}
                  onChange={(e) => handleInputChange("address", e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="civilStatus">
                  {t("civilStatus") || "Civil Status"}
                </Label>
                <Input
                  id="civilStatus"
                  placeholder="Single / Married / Widowed"
                  value={formData.civilStatus}
                  onChange={(e) =>
                    handleInputChange("civilStatus", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="occupation">
                  {t("occupation") || "Occupation"}
                </Label>
                <Input
                  id="occupation"
                  placeholder="Employee / Business Owner / Student"
                  value={formData.occupation}
                  onChange={(e) =>
                    handleInputChange("occupation", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="contactNumber">
                  {t("contactNumber") || "Contact Number"}
                </Label>
                <Input
                  id="contactNumber"
                  placeholder="+63 917 123 4567"
                  value={formData.contactNumber}
                  onChange={(e) =>
                    handleInputChange("contactNumber", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="date">{t("dateToday") || "Date Today"} *</Label>
                <Input
                  id="date"
                  type="date"
                  value={formData.date}
                  onChange={(e) => handleInputChange("date", e.target.value)}
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="incidentDate">
                  {t("incidentDate") || "Date of Incident"}
                </Label>
                <Input
                  id="incidentDate"
                  type="date"
                  value={formData.incidentDate}
                  onChange={(e) =>
                    handleInputChange("incidentDate", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="incidentLocation">
                  {t("incidentLocation") || "Location of Incident"}
                </Label>
                <Input
                  id="incidentLocation"
                  placeholder="Where did the incident happen?"
                  value={formData.incidentLocation}
                  onChange={(e) =>
                    handleInputChange("incidentLocation", e.target.value)
                  }
                />
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label htmlFor="additionalDetails">
                  {t("additionalDetails") || "Additional Details (Optional)"}
                </Label>
                <Textarea
                  id="additionalDetails"
                  placeholder="Any additional information you want to include..."
                  value={formData.additionalDetails}
                  onChange={(e) =>
                    handleInputChange("additionalDetails", e.target.value)
                  }
                  rows={3}
                />
              </div>

              {/* Include Title Page Option */}
              <div className="md:col-span-2 pt-2">
                <label className="flex items-center gap-3 cursor-pointer group">
                  <input
                    type="checkbox"
                    checked={includeTitlePage}
                    onChange={(e) => setIncludeTitlePage(e.target.checked)}
                    className="w-5 h-5 rounded border-2 border-primary text-primary focus:ring-primary cursor-pointer"
                  />
                  <span className="text-sm font-medium group-hover:text-primary transition-colors">
                    Include LegAIze Title Page (Cover Page)
                  </span>
                </label>
                <p className="text-xs text-muted-foreground mt-1 ml-8">
                  Adds a professional cover page with LegAIze branding, your
                  name, and reference number
                </p>
              </div>
            </div>
          ) : (
            <div className="grid grid-cols-2 md:grid-cols-3 gap-4 text-sm">
              <div>
                <span className="text-muted-foreground">Name:</span>
                <p className="font-medium">
                  {formData.fullName || "Not provided"}
                </p>
              </div>
              <div>
                <span className="text-muted-foreground">Age:</span>
                <p className="font-medium">{formData.age || "Not provided"}</p>
              </div>
              <div>
                <span className="text-muted-foreground">Date:</span>
                <p className="font-medium">{formatDate(formData.date)}</p>
              </div>
              <div className="col-span-2 md:col-span-3">
                <span className="text-muted-foreground">Address:</span>
                <p className="font-medium">
                  {formData.address || "Not provided"}
                </p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Report Type Selection */}
      <Tabs
        value={activeReport}
        onValueChange={setActiveReport}
        className="w-full no-print"
      >
        <TabsList className="w-full justify-start h-auto p-1.5 bg-secondary/50 backdrop-blur-sm rounded-xl no-print">
          <TabsTrigger
            value="salaysay"
            className="gap-2 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
          >
            <FileSignature className="h-4 w-4" />
            <span className="hidden sm:inline">Salaysay</span>
          </TabsTrigger>
          <TabsTrigger
            value="summary"
            className="gap-2 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
          >
            <ClipboardList className="h-4 w-4" />
            <span className="hidden sm:inline">Case Summary</span>
          </TabsTrigger>
          <TabsTrigger
            value="legal"
            className="gap-2 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
          >
            <Scale className="h-4 w-4" />
            <span className="hidden sm:inline">Legal Brief</span>
          </TabsTrigger>
        </TabsList>

        {/* Salaysay Tab */}
        <TabsContent value="salaysay" className="mt-6">
          <Card>
            <CardHeader className="pb-3 no-print">
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <FileSignature className="h-5 w-5 text-primary" />
                  Sinumpaang Salaysay (Sworn Statement)
                </CardTitle>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handlePrint}
                    className="gap-2"
                  >
                    <Printer className="h-4 w-4" />
                    Print
                  </Button>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                    className="gap-2"
                  >
                    {isDownloading ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="h-4 w-4" />
                    )}
                    {isDownloading ? "Downloading..." : "Download PDF"}
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              {/* Printable Salaysay Document */}
              <div ref={printRef} className="print-wrapper">
                {/* Title Page */}
                {includeTitlePage && (
                  <TitlePage
                    formData={formData}
                    analysis={analysis}
                    formatDate={formatDate}
                  />
                )}

                <div
                  className="print-document bg-white text-black p-8 rounded-lg border"
                  style={{ pageBreakInside: "auto" }}
                >
                  <div
                    className="text-center mb-8 no-break"
                    style={{ pageBreakInside: "avoid" }}
                  >
                    <h1 className="text-xl font-bold uppercase tracking-wide">
                      SINUMPAANG SALAYSAY
                    </h1>
                    <p className="text-sm text-gray-600">(Sworn Statement)</p>
                  </div>

                  <div className="space-y-6 text-sm leading-relaxed">
                    <p className="text-justify">
                      <strong>AKO</strong>, si{" "}
                      <span className="underline font-semibold px-2">
                        {formData.fullName || "________________________"}
                      </span>
                      , may sapat na gulang,{" "}
                      {formData.age
                        ? `${formData.age} taong gulang`
                        : "_____ taong gulang"}
                      ,
                      {formData.civilStatus
                        ? ` ${formData.civilStatus}`
                        : " _____________"}
                      ,
                      {formData.occupation
                        ? ` ${formData.occupation}`
                        : " _____________"}{" "}
                      ang hanapbuhay, at kasalukuyang naninirahan sa{" "}
                      <span className="underline px-1">
                        {formData.address ||
                          "________________________________________________"}
                      </span>
                      , matapos makapanumpa ng naaayon sa batas, ay malaya at
                      kusang-loob na nagpapahayag ng mga sumusunod:
                    </p>

                    <div className="pl-8 space-y-4">
                      <p className="text-justify">
                        <strong>1.</strong> Na noong{" "}
                        <span className="underline px-1">
                          {formatDate(formData.incidentDate)}
                        </span>
                        , sa{" "}
                        <span className="underline px-1">
                          {formData.incidentLocation ||
                            "________________________"}
                        </span>
                        , ay naganap ang mga sumusunod na pangyayari:
                      </p>

                      <div className="bg-gray-50 p-4 rounded border-l-4 border-gray-400 min-h-[100px]">
                        <p className="text-justify whitespace-pre-wrap">
                          {analysis?.caseType && (
                            <span>
                              <strong>Uri ng Kaso:</strong> {analysis.caseType}
                              <br />
                              <br />
                            </span>
                          )}
                          {formData.additionalDetails ||
                            "[Ilagay dito ang detalyadong salaysay ng pangyayari]"}
                        </p>
                      </div>

                      <p className="text-justify">
                        <strong>2.</strong> Na ang mga sumusunod ay ang aking
                        mga karapatan kaugnay sa nasabing pangyayari:
                      </p>

                      {analysis?.rights && analysis.rights.length > 0 && (
                        <ul className="list-disc pl-8 space-y-1">
                          {analysis.rights.map((right, index) => (
                            <li key={index} className="text-justify">
                              {right}
                            </li>
                          ))}
                        </ul>
                      )}

                      <p className="text-justify">
                        <strong>3.</strong> Na ang mga sumusunod na batas ay
                        maaaring naaangkop sa aking kaso:
                      </p>

                      {analysis?.relevantLaws &&
                        analysis.relevantLaws.length > 0 && (
                          <ul className="list-disc pl-8 space-y-1">
                            {analysis.relevantLaws
                              .slice(0, 5)
                              .map((law, index) => (
                                <li key={index} className="text-justify">
                                  <strong>{law.title || law.name}</strong>
                                  {(law.law || law.article) &&
                                    ` - ${law.law || law.article}`}
                                </li>
                              ))}
                          </ul>
                        )}

                      <p className="text-justify">
                        <strong>4.</strong> Na ang lahat ng aking sinabi sa
                        salaysay na ito ay pawang katotohanan at wala akong
                        idinagdag o inalis na anuman.
                      </p>

                      <p className="text-justify">
                        <strong>5. </strong> Na ginawa ko ang salaysay na ito
                        upang magsilbing patunay sa anumang legal na aksyon na
                        maaaring isagawa kaugnay ng nasabing pangyayari.
                      </p>
                    </div>

                    <p className="text-justify mt-8">
                      <strong>SA KATUNAYAN NG LAHAT NG ITO</strong>, ako ay
                      lumagda sa ibaba nito ngayong
                      <span className="underline font-semibold px-2">
                        {formatDate(formData.date)}
                      </span>
                      , dito sa{" "}
                      <span className="underline px-1">
                        {formData.address?.split(",").pop()?.trim() ||
                          "________________________"}
                      </span>
                      , Pilipinas.
                    </p>

                    <div
                      className="mt-16 flex justify-between no-break"
                      style={{ pageBreakInside: "avoid" }}
                    >
                      <div className="text-center">
                        <div className="border-b border-black w-48 mb-2"></div>
                        <p className="text-sm font-semibold">
                          {formData.fullName?.toUpperCase() ||
                            "PANGALAN NG NAGPAPAHAYAG"}
                        </p>
                        <p className="text-xs text-gray-600">
                          Nagpapahayag/Affiant
                        </p>
                      </div>
                      <div className="text-center">
                        <div className="border-b border-black w-48 mb-2"></div>
                        <p className="text-sm">Petsa/Date</p>
                      </div>
                    </div>

                    <div
                      className="mt-12 pt-8 border-t border-gray-300 no-break"
                      style={{ pageBreakInside: "avoid" }}
                    >
                      <p className="text-center font-bold mb-4">
                        PAGPAPATUNAY NG NOTARYO PUBLIKO
                      </p>
                      <p className="text-justify text-xs">
                        SUBSCRIBED AND SWORN to before me this _____ day of
                        _______________, 20_____ at _________________________,
                        Philippines, affiant exhibiting to me his/her valid
                        government-issued ID No. ________________________ issued
                        on __________________ at ________________________.
                      </p>
                      <div className="mt-8 text-center">
                        <div className="border-b border-black w-48 mx-auto mb-2"></div>
                        <p className="text-sm">NOTARYO PUBLIKO/Notary Public</p>
                        <p className="text-xs text-gray-600 mt-4">
                          Doc. No. _____; Page No. _____; Book No. _____; Series
                          of 20_____.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Case Summary Tab */}
        <TabsContent value="summary" className="mt-6">
          <Card>
            <CardHeader className="pb-3 no-print">
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <ClipboardList className="h-5 w-5 text-primary" />
                  Case Summary Report
                </CardTitle>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handlePrint}
                    className="gap-2"
                  >
                    <Printer className="h-4 w-4" />
                    Print
                  </Button>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                    className="gap-2"
                  >
                    {isDownloading ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="h-4 w-4" />
                    )}
                    {isDownloading ? "Downloading..." : "Download PDF"}
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              {/* Printable Summary Document */}
              <div className="print-wrapper">
                {/* Title Page */}
                {includeTitlePage && (
                  <TitlePage
                    formData={formData}
                    analysis={analysis}
                    formatDate={formatDate}
                  />
                )}

                <div
                  className="print-document bg-white text-black p-8 rounded-lg border"
                  style={{ pageBreakInside: "auto" }}
                >
                  <div
                    className="text-center mb-6 pb-4 border-b-2 border-gray-800 no-break"
                    style={{ pageBreakInside: "avoid" }}
                  >
                    <h1 className="text-xl font-bold uppercase tracking-wide">
                      CASE SUMMARY REPORT
                    </h1>
                    <p className="text-sm text-gray-600 mt-1">
                      Legal Analysis and Recommendations
                    </p>
                  </div>

                  <div className="grid grid-cols-2 gap-4 mb-6 text-sm">
                    <div>
                      <p className="text-gray-600">Report Date:</p>
                      <p className="font-semibold">
                        {formatDate(formData.date)}
                      </p>
                    </div>
                    <div>
                      <p className="text-gray-600">Reference No:</p>
                      <p className="font-semibold">
                        CASE-{Date.now().toString().slice(-8)}
                      </p>
                    </div>
                  </div>

                  <Separator className="my-4 bg-gray-300" />

                  {/* Follow-up Questions & Answers */}
                  {analysis?.followUpQuestions &&
                    analysis.followUpQuestions.length > 0 && (
                      <div className="mb-6">
                        <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                          I. ADDITIONAL INFORMATION
                        </h2>
                        <p className="text-sm text-gray-600 mb-4">
                          The following information was gathered through
                          follow-up questions:
                        </p>
                        <div className="space-y-4">
                          {analysis.followUpQuestions.map((qa, index) => (
                            <div
                              key={index}
                              className="bg-gray-50 p-4 rounded border-l-4 border-primary"
                            >
                              <p className="font-semibold text-sm mb-2 text-gray-800">
                                Q{index + 1}: {qa.question}
                              </p>
                              <p className="text-sm text-gray-700 leading-relaxed">
                                {qa.answer || "No answer provided"}
                              </p>
                            </div>
                          ))}
                        </div>
                        <Separator className="my-6 bg-gray-300" />
                      </div>
                    )}

                  {/* Client Information */}
                  <div className="mb-6">
                    <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                      {analysis?.followUpQuestions &&
                      analysis.followUpQuestions.length > 0
                        ? "II. CLIENT INFORMATION"
                        : "I. CLIENT INFORMATION"}
                    </h2>
                    <div className="grid grid-cols-2 gap-3 text-sm bg-gray-50 p-4 rounded">
                      <div>
                        <span className="text-gray-600">Name:</span>
                        <span className="font-semibold ml-2">
                          {formData.fullName || "N/A"}
                        </span>
                      </div>
                      <div>
                        <span className="text-gray-600">Age:</span>
                        <span className="font-semibold ml-2">
                          {formData.age || "N/A"}
                        </span>
                      </div>
                      <div className="col-span-2">
                        <span className="text-gray-600">Address:</span>
                        <span className="font-semibold ml-2">
                          {formData.address || "N/A"}
                        </span>
                      </div>
                      <div>
                        <span className="text-gray-600">Contact:</span>
                        <span className="font-semibold ml-2">
                          {formData.contactNumber || "N/A"}
                        </span>
                      </div>
                      <div>
                        <span className="text-gray-600">Incident Date:</span>
                        <span className="font-semibold ml-2">
                          {formatDate(formData.incidentDate) || "N/A"}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Case Overview */}
                  <div className="mb-6">
                    <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                      {analysis?.followUpQuestions &&
                      analysis.followUpQuestions.length > 0
                        ? "III. CASE OVERVIEW"
                        : "II. CASE OVERVIEW"}
                    </h2>
                    <div className="bg-gray-50 p-4 rounded text-sm space-y-2">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Case Type:</span>
                        <span className="font-bold">
                          {analysis?.caseType || "General Legal Inquiry"}
                        </span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Severity Level:</span>
                        <span className="font-bold">{getSeverityText()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Location:</span>
                        <span className="font-semibold">
                          {formData.incidentLocation || "Not specified"}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Applicable Laws */}
                  <div className="mb-6">
                    <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                      {analysis?.followUpQuestions &&
                      analysis.followUpQuestions.length > 0
                        ? "IV. APPLICABLE LAWS"
                        : "III. APPLICABLE LAWS"}
                    </h2>
                    <div className="text-sm space-y-2">
                      {analysis?.relevantLaws &&
                      analysis.relevantLaws.length > 0 ? (
                        analysis.relevantLaws.map((law, index) => (
                          <div
                            key={index}
                            className="p-3 bg-gray-50 rounded border-l-4 border-gray-400"
                          >
                            <p className="font-semibold">
                              {law.title || law.name}
                            </p>
                            {(law.law || law.article) && (
                              <p className="text-gray-600 text-xs">
                                {law.law || law.article}
                              </p>
                            )}
                            {law.description && (
                              <p className="text-gray-700 mt-1 text-xs">
                                {law.description}
                              </p>
                            )}
                          </div>
                        ))
                      ) : (
                        <p className="text-gray-600">
                          No specific laws identified.
                        </p>
                      )}
                    </div>
                  </div>

                  {/* Client Rights */}
                  <div className="mb-6">
                    <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                      {analysis?.followUpQuestions &&
                      analysis.followUpQuestions.length > 0
                        ? "V. CLIENT RIGHTS"
                        : "IV. CLIENT RIGHTS"}
                    </h2>
                    <ul className="text-sm space-y-1 list-disc pl-5">
                      {analysis?.rights && analysis.rights.length > 0 ? (
                        analysis.rights.map((right, index) => (
                          <li key={index}>{right}</li>
                        ))
                      ) : (
                        <li>Standard legal rights apply.</li>
                      )}
                    </ul>
                  </div>

                  {/* Recommended Actions */}
                  <div className="mb-6">
                    <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                      {analysis?.followUpQuestions &&
                      analysis.followUpQuestions.length > 0
                        ? "VI. RECOMMENDED ACTIONS"
                        : "V. RECOMMENDED ACTIONS"}
                    </h2>
                    <div className="text-sm space-y-4">
                      {analysis?.nextSteps && analysis.nextSteps.length > 0 ? (
                        analysis.nextSteps.map((step, index) => (
                          <div
                            key={index}
                            className="flex flex-col sm:flex-row items-start gap-4 p-3 bg-gray-50 rounded border border-gray-200"
                          >
                            {/* Step Image */}
                            <div className="shrink-0 w-full sm:w-32">
                              <StepImage
                                stepText={step.action}
                                stepNumber={index + 1}
                                className="w-full"
                              />
                            </div>

                            {/* Step Content */}
                            <div className="flex-1 flex items-start gap-3">
                              <span className="font-bold text-gray-700 shrink-0">
                                {index + 1}.
                              </span>
                              <div className="flex-1">
                                <p>{step.action}</p>
                                {step.deadline && (
                                  <p className="text-xs text-gray-600 mt-1">
                                    Deadline: {step.deadline}
                                  </p>
                                )}
                              </div>
                              <Badge
                                variant={
                                  step.priority === "high"
                                    ? "destructive"
                                    : "secondary"
                                }
                                className="ml-auto text-xs shrink-0"
                              >
                                {step.priority?.toUpperCase()}
                              </Badge>
                            </div>
                          </div>
                        ))
                      ) : (
                        <p className="text-gray-600">
                          Consult with a licensed attorney for specific
                          recommendations.
                        </p>
                      )}
                    </div>
                  </div>

                  {/* Cost Estimate */}
                  {analysis?.estimatedCosts && (
                    <div className="mb-6">
                      <h2 className="font-bold text-sm uppercase tracking-wide mb-3 text-gray-700">
                        VI. ESTIMATED COSTS
                      </h2>
                      <div className="bg-gray-50 p-4 rounded text-sm space-y-2">
                        {analysis.estimatedCosts.consultationFee && (
                          <div className="flex justify-between">
                            <span>Consultation Fee:</span>
                            <span className="font-semibold">
                              {analysis.estimatedCosts.consultationFee}
                            </span>
                          </div>
                        )}
                        {analysis.estimatedCosts.filingFees && (
                          <div className="flex justify-between">
                            <span>Filing Fees:</span>
                            <span className="font-semibold">
                              {analysis.estimatedCosts.filingFees}
                            </span>
                          </div>
                        )}
                        {analysis.estimatedCosts.totalEstimated && (
                          <div className="flex justify-between border-t pt-2 mt-2">
                            <span className="font-bold">Total Estimated:</span>
                            <span className="font-bold">
                              {analysis.estimatedCosts.totalEstimated}
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {/* Footer */}
                  {/* Footer */}
                  <div className="mt-8 pt-4 border-t-2 border-gray-800 text-xs text-gray-600">
                    <p className="text-center mb-4">
                      <strong>DISCLAIMER:</strong> This report is generated for
                      informational purposes only and does not constitute legal
                      advice. Please consult with a licensed attorney for
                      professional legal counsel.
                    </p>
                    <div className="flex justify-between">
                      <span>Generated: {formatDate(formData.date)}</span>
                      <span>Page 1 of 1</span>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Legal Brief Tab */}
        <TabsContent value="legal" className="mt-6">
          <Card>
            <CardHeader className="pb-3 no-print">
              <div className="flex items-center justify-between">
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Scale className="h-5 w-5 text-primary" />
                  Legal Brief / Memorandum
                </CardTitle>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handlePrint}
                    className="gap-2"
                  >
                    <Printer className="h-4 w-4" />
                    Print
                  </Button>
                  <Button
                    variant="default"
                    size="sm"
                    onClick={handleDownloadPDF}
                    disabled={isDownloading}
                    className="gap-2"
                  >
                    {isDownloading ? (
                      <Loader2 className="h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="h-4 w-4" />
                    )}
                    {isDownloading ? "Downloading..." : "Download PDF"}
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              {/* Printable Legal Brief */}
              <div className="print-wrapper">
                {/* Title Page */}
                {includeTitlePage && (
                  <TitlePage
                    formData={formData}
                    analysis={analysis}
                    formatDate={formatDate}
                  />
                )}

                <div
                  className="print-document bg-white text-black p-8 rounded-lg border font-serif"
                  style={{ pageBreakInside: "auto" }}
                >
                  <div
                    className="text-center mb-8 no-break"
                    style={{ pageBreakInside: "avoid" }}
                  >
                    <p className="text-sm text-gray-600">
                      Republic of the Philippines
                    </p>
                    <p className="text-sm text-gray-600 mb-4">
                      OFFICE OF THE LEGAL COUNSEL
                    </p>
                    <h1 className="text-lg font-bold uppercase tracking-wide border-b-2 border-black pb-2 inline-block">
                      LEGAL MEMORANDUM
                    </h1>
                  </div>

                  <div className="space-y-4 text-sm">
                    <div className="grid grid-cols-[100px_1fr] gap-2">
                      <span className="font-bold">TO:</span>
                      <span>
                        {formData.fullName?.toUpperCase() || "[CLIENT NAME]"}
                      </span>

                      <span className="font-bold">FROM:</span>
                      <span>Legal Analysis System</span>

                      <span className="font-bold">DATE:</span>
                      <span>{formatDate(formData.date)}</span>

                      <span className="font-bold">RE:</span>
                      <span className="font-semibold">
                        {analysis?.caseType || "Legal Matter"} - Legal Analysis
                        and Opinion
                      </span>
                    </div>

                    <Separator className="my-6 bg-gray-800" />

                    {/* I. Statement of Facts */}
                    <div>
                      <h2 className="font-bold uppercase mb-3">
                        I. STATEMENT OF FACTS
                      </h2>
                      <p className="text-justify leading-relaxed pl-4">
                        The client, {formData.fullName || "[Client Name]"},{" "}
                        {formData.age ? `${formData.age} years of age` : ""},
                        residing at {formData.address || "[Address]"}, seeks
                        legal advice regarding a matter classified as
                        <strong>
                          {" "}
                          {analysis?.caseType || "a legal concern"}
                        </strong>
                        .
                        {formData.incidentDate && (
                          <span>
                            {" "}
                            The incident in question occurred on{" "}
                            {formatDate(formData.incidentDate)}
                          </span>
                        )}
                        {formData.incidentLocation && (
                          <span> at {formData.incidentLocation}</span>
                        )}
                        .
                      </p>
                      {formData.additionalDetails && (
                        <p className="text-justify leading-relaxed pl-4 mt-2">
                          Additional details provided:{" "}
                          {formData.additionalDetails}
                        </p>
                      )}
                    </div>

                    {/* II. Issues */}
                    <div>
                      <h2 className="font-bold uppercase mb-3">II. ISSUES</h2>
                      <p className="text-justify pl-4">
                        1. What are the legal rights of the client under the
                        circumstances?
                        <br />
                        2. What laws and regulations are applicable to this
                        case?
                        <br />
                        3. What are the recommended courses of action?
                      </p>
                    </div>

                    {/* III. Discussion */}
                    <div>
                      <h2 className="font-bold uppercase mb-3">
                        III. DISCUSSION
                      </h2>

                      <p className="text-justify pl-4 mb-3">
                        <strong>A. Applicable Laws and Jurisprudence</strong>
                      </p>
                      <div className="pl-8 space-y-2">
                        {analysis?.relevantLaws &&
                        analysis.relevantLaws.length > 0 ? (
                          analysis.relevantLaws.map((law, index) => (
                            <p key={index} className="text-justify">
                              <strong>
                                {index + 1}. {law.title || law.name}
                              </strong>
                              {(law.law || law.article) && (
                                <span className="text-gray-600">
                                  {" "}
                                  ({law.law || law.article})
                                </span>
                              )}
                              {law.description && (
                                <span> - {law.description}</span>
                              )}
                            </p>
                          ))
                        ) : (
                          <p className="text-gray-600">
                            Further legal research is required to identify
                            specific applicable laws.
                          </p>
                        )}
                      </div>

                      <p className="text-justify pl-4 mt-4 mb-3">
                        <strong>B. Rights of the Client</strong>
                      </p>
                      <div className="pl-8">
                        <p className="text-justify mb-2">
                          Under the applicable laws, the client is entitled to
                          the following rights:
                        </p>
                        <ul className="list-disc pl-5 space-y-1">
                          {analysis?.rights && analysis.rights.length > 0 ? (
                            analysis.rights.map((right, index) => (
                              <li key={index}>{right}</li>
                            ))
                          ) : (
                            <li>
                              Standard constitutional and statutory rights as
                              provided by law.
                            </li>
                          )}
                        </ul>
                      </div>
                    </div>

                    {/* IV. Conclusion and Recommendations */}
                    <div>
                      <h2 className="font-bold uppercase mb-3">
                        IV. CONCLUSION AND RECOMMENDATIONS
                      </h2>
                      <p className="text-justify pl-4 mb-3">
                        Based on the foregoing analysis, it is respectfully
                        recommended that the client:
                      </p>
                      <div className="space-y-4">
                        {analysis?.nextSteps &&
                        analysis.nextSteps.length > 0 ? (
                          analysis.nextSteps.map((step, index) => (
                            <div
                              key={index}
                              className="flex flex-col sm:flex-row items-start gap-4 p-3 bg-gray-50 rounded border border-gray-200"
                            >
                              {/* Step Image */}
                              <div className="shrink-0 w-full sm:w-32">
                                <StepImage
                                  stepText={step.action}
                                  stepNumber={index + 1}
                                  className="w-full"
                                />
                              </div>

                              {/* Step Content */}
                              <div className="flex-1">
                                <p className="text-justify">
                                  <strong>{index + 1}.</strong> {step.action}
                                  {step.priority === "high" && (
                                    <span className="text-red-600 font-semibold">
                                      {" "}
                                      (URGENT)
                                    </span>
                                  )}
                                </p>
                              </div>
                            </div>
                          ))
                        ) : (
                          <ol className="list-decimal pl-12 space-y-2">
                            <li>
                              Consult with a licensed attorney for professional
                              legal advice.
                            </li>
                            <li>Gather all relevant documents and evidence.</li>
                            <li>
                              File the appropriate legal actions within the
                              prescribed period.
                            </li>
                          </ol>
                        )}
                      </div>
                    </div>

                    {/* Signature */}
                    <div className="mt-12 pt-8">
                      <p className="text-right">Respectfully submitted,</p>
                      <div className="mt-8 text-right">
                        <div className="border-b border-black w-48 ml-auto mb-2"></div>
                        <p className="font-semibold">Legal Analysis System</p>
                        <p className="text-xs text-gray-600">
                          AI-Powered Legal Assistant
                        </p>
                      </div>
                    </div>

                    {/* Disclaimer */}
                    <div className="mt-8 pt-4 border-t text-xs text-gray-600 italic">
                      <p>
                        <strong>Note:</strong> This memorandum is prepared based
                        on the information provided and is intended for general
                        guidance only. It does not constitute formal legal
                        advice and should not be relied upon as such. For
                        specific legal matters, please consult with a duly
                        licensed attorney in the Philippines.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
